services:
  postgres:
    image: postgres:16.3-alpine3.20
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_LOGIN:?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}
      POSTGRES_DB: ${DB_NAME:?}
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
