services:
  postgres:
    image: postgres:16.3-alpine3.20
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_LOGIN:?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}
      POSTGRES_DB: ${DB_NAME:?}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  main-app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      DB_HOST: ${DB_HOST:?}
      DB_PORT: ${DB_PORT:?}
      DB_LOGIN: ${DB_LOGIN:?}
      DB_PASSWORD: ${DB_PASSWORD:?}
      DB_NAME: ${DB_NAME:?}
  
    volumes:
      - ./src:/app/src

    ports: 
      - "8000:8000"

    depends_on:
      - postgres

    command: "uvicorn --factory src.presentation.api.main:create_app --timeout-graceful-shutdown 2 --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
